# model: [olx_name, displayed_name, autovit_name],
#TODO GRAB MODELS OLX INSTEAD OF MANUAL, AUTOVIT IS DONE

CAR_BRANDS_MODELS = [
    {
        "olxBrand": "volkswagen",
        "brand": "Volkswagen",
        "models": [
            ['181', '181', '181'],
            ['amarok', 'Amarok', 'amarok'],
            ['arteon', 'Arteon', 'arteon'],
            ['atlas', 'Atlas', 'atlas'],
            ['beetle', 'Beetle', 'beetle'],
            ['bora', 'Bora', 'bora'],
            ['buggy', 'Buggy', 'buggy'],
            ['caddy', 'Caddy', 'caddy'],
            ['california', 'California', 'california'],
            ['caravelle', 'Caravelle', 'caravelle'],
            ['corrado', 'Corrado', 'corrado'],
            ['crafter', 'Crafter', 'crafter'],
            ['e-golf', 'e-Golf', 'e-golf'],
            ['eos', 'Eos', 'eos'],
            ['fox', 'Fox', 'fox'],
            ['garbus', 'Garbus', 'garbus'],
            ['golf', 'Golf', 'golf'],
            ['golf-plus', 'Golf Plus', 'golf-plus'],
            ['ID-4', 'ID-4', 'id-4'],
            ['id-buzz', 'ID Buzz', 'id-buzz'],
            ['id3', 'ID3', 'id3'],
            ['id5', 'ID5', 'id5'],
            ['iltis', 'Iltis', 'iltis'],
            ['jetta', 'Jetta', 'jetta'],
            ['kafer', 'Kafer', 'kafer'],
            ['karmann-ghia', 'Karmann-Ghia', 'karmann-ghia'],
            ['lupo', 'Lupo', 'lupo'],
            ['multivan', 'Multivan', 'multivan'],
            ['new-beetle', 'New Beetle', 'new-beetle'],
            ['passat', 'Passat', 'passat'],
            ['passat-alltrack', 'Passat Alltrack', 'passat-alltrack'],
            ['passat-cc', 'Passat CC', 'passat-cc'],
            ['phaeton', 'Phaeton', 'phaeton'],
            ['polo', 'Polo', 'polo'],
            ['santana', 'Santana', 'santana'],
            ['scirocco', 'Scirocco', 'scirocco'],
            ['sharan', 'Sharan', 'sharan'],
            ['t-cross', 'T-Cross', 't-cross'],
            ['taigo', 'Taigo', 'taigo'],
            ['tiguan', 'Tiguan', 'tiguan'],
            ['t-roc', 'T-Roc', 't-roc'],
            ['touran', 'Touran', 'touran'],
            ['touareg', 'Touareg', 'touareg'],
            ['transporter', 'Transporter', 'transporter'],
            ['up', 'Up!', 'up'],
            ['vento', 'Vento', 'vento'],
            ['vw-golf-sv', 'Golf Sportvan', 'vw-golf-sv'],
        ]
    },
    {
        "olxBrand": "audi",
        "brand": "Audi",
        "models": [
            ["a1", "A1", "a1"],
            ["a2", "A2", "a2"], # OLX
            ["a3", "A3", "a3"], # OLX
            ["a4", "A4", "a4"], # OLX
            ["a4-allroad", "A4 Allroad", "a4-allroad"],
            ["a5", "A5", "a5"], # OLX
            ["a6", "A6", "a6"], # OLX
            ["a6-allroad", "A6 Allroad", "a6-allroad"],
            ["a7", "A7", "a7"], # OLX
            ["a8", "A8", "a8"], # OLX
            ["audi-rsq3", "RS Q3", "audi-rsq3"],
            ["audi-s1", "S1", "audi-s1"],
            ["audi-sq2", "SQ1", "audi-sq2"],
            ["cabriolet", "Cabriolet", "cabriolet"],
            ["coupe", "Coupe", "coupe"],
            ["e-tron", "e-tron", "e-tron"],
            ["q2", "Q2", "q2"],
            ["q3", "Q3", "q3"], # OLX
            ["q4", "Q4", "q4"],
            ["q5", "Q5", "q5"], # OLX
            ["q7", "Q7", "q7"], # OLX
            ["q8", "Q8", "q8"],
            ["quattro", "Quattro", "quattro"],
            ["r8", "R8", "r8"],
            ["rs2", "RS2", "rs2"],
            ["rs3", "RS3", "rs3"],
            ["rs4", "RS4", "rs4"],
            ["rs5", "RS5", "rs5"],
            ["rs6", "RS6", "rs6"],
            ["rs7", "RS7", "rs7"],
            ["rs-q8", "RS Q8", "rs-q8"],
            ["s2", "S2", "s2"],
            ["s3", "S3", "s3"],
            ["s4", "S4", "s4"],
            ["s5", "S5", "s5"],
            ["s6", "S6", "s6"],
            ["s7", "S7", "s7"],
            ["s8", "S8", "s8"],
            ["sq5", "SQ5", "sq5"],
            ["sq7", "SQ7", "sq7"],
            ["sq8", "SQ8", "sq8"],
            ["tt", "TT", "tt"],
            ["tt-rs", "TT RS", "tt-rs"],
            ["tt-s", "TT S", "tt-s"],
            ["v8", "V8", "v8"],
            ["80", "80", "80"],
            ["90", "90", "90"],
            ["100", "100", "100"],
            ["200", "200", "200"],
        ]
    },
    {
        "olxBrand": "abarth",
        "brand": "Abarth",
        "models": [
            ["124", "124", "124"],
            ["124-spider", "124 Spider", "124-spider"],
            ["500", "500", "500"],
            ["595", "595", "595"],
            ["695", "695", "695"],
            ["grande-punto", "Grande Punto", "grande-punto"],
        ]
    },
    {
        "olxBrand": "acura",
        "brand": "Acura",
        "models": [
            ["cl", "CL", "cl_classe"],
            ["csx", "CSX", "csx"],
            ["el-", "EL", "el"],
            ["ilx", "ILX", "ilx"],
            ["integra", "Integra", "integra"],
            ["legend", "Legend", "legend"],
            ["mdx", "MDX", "mdx"],
            ["nsx", "NSX", "nsx"],
            ["rdx", "RDX", "rdx"],
            ["rl", "RL", "rl"],
            ["rlx", "RSX", "rlx"],
            ["rsx", "RSX", "rsx"],
            ["tl", "TL", "tl"],
            ["tlx", "TLX", "tlx"],
            ["tsx", "TSX", "tsx"],
            ["vigor", "Vigor", "vigor"],
            ["zdx", "ZDX", "zdx"],
        ]
    },
    {
        "olxBrand": "aixam",
        "brand": "Aixam",
        "models": [
            ["city", "City", "city"],
            ["coupe", "Coupe", "coupe"],
            ["crossline", "Crossline", "crossline"],
            ["crossover", "Crossover", "crossover"],
            ["d-truck", "D-Truck", "d-truck"],
            ["e-truck", "e-Truck", "e-truck"],
            ["gto", "GTO", ""],
            ["miniauto", "Miniauto", "miniauto"],
            ["roadline", "Roadline", "roadline"],
            ["scouty-r", "Scouty-R", "scouty-r"],
            ["seria-a", "Series A", "seria-a"],
        ]
    },
    {
        "olxBrand": "alfa-romeo",
        "brand": "Alfa Romeo",
        "models": [
            ["4c", "4C", "4c"],
            ["33", "33", "33"],
            ["75", "75", "75"],
            ["90", "90", "90"],
            ["145", "145", "145"],
            ["146", "146", "146"],
            ["147", "147", "147"],
            ["155", "155", "155"],
            ["156", "156", "156"],
            ["159", "159", "159"], # OLX
            ["164", "164", "164"],
            ["166", "166", "166"],
            ["alfasud", "Alfasud", "alfasud"],
            ["alfetta", "Alfetta", "alfetta"],
            ["", "Crosswagon", "crosswagon"],
            ["brera", "Brera", "brera"],
            ["giulia", "Giulia", "giulia"],
            ["giulietta", "Giulietta", "giulietta"],
            ["gt", "GT", "gt"],
            ["gtv", "GTV", "gtv"],
            ["mito", "MiTo", "mito"],
            ["rs-sz", "RZ-SZ", ""],
            ["spider", "Spider", "spider"],
            ["sprint", "Sprint", "sprint"],
            ["stelvio", "Stelvio", "stelvio"],
            ["", "Tonale", "tonale"]
        ]
    },
    {
        "olxBrand": "aro",
        "brand": "Aro",
        "models": [
            ["seria-10", "Series 10", "seria-10"], 
            ["seria-240", "Series 240", "seria-240"],
            ["seria-ims", "Series IMS", "seria-ims"],
            ["spartana", "Spartan", "spartana"],
        ]
    },
    {
        "olxBrand": "aston-martin",
        "brand": "Aston Martin",
        "models": [
            ["amv8", "AMV8", "amv8"],
            ["bulldog", "Bulldog", "bulldog"],
            ["cygnet", "Cygnet", "cygnet"],
            ["db4", "DB4", "db4"],
            ["db5", "DB5", "db5"],
            ["db6", "DB6", "db6"],
            ["db7", "DB7", "db7"],
            ["db9", "DB9", "db9"],
            ["db11", "DB11", "db11"],
            ["dbs", "DBS", "dbs"],
            ["dbx", "DBX", "dbx"],
            ["lagonda", "Lagonda", "lagonda"],
            ["one-77", "One-77", "one-77"],
            ["", "Rapide", "rapide"],
            ["vanquish", "Vanquish", "vanquish"],
            ["v8-vantage", "V8 Vantage", "v8-vantage"],
            ["v8-zagato", "V8 Zagato", "v8-zagato"],
            ["v12-vantage", "V12 Vantage", "v12-vantage"],
            ["virage", "Virage", "virage"],
            ["volatne", "Volatne", "volatne"],
        ]
    },
    {
        "olxBrand": "bentley",
        "brand": "Bentley",
        "models": [
            ["arnage", "Arnage", "arnage"],
            ["azure", "Azure", "azure"],
            ["bentayga", "Bentayga", "bentayga"],
            ["brooklands", "Brooklands", "brooklands"],
            ["continental", "Continental", "continental"],
            ["eight", "Eight", "eight"],
            ["flying-spur-", "Flying Spur", "flying-spur"],
            ["mulliner", "Mulliner", "mulliner"],
            ["mulsanne", "Mulsanne", "mulsanne"],
            ["turbo-rt", "Turbo", "turbo-rt"],
        ]
    },
    {
        "olxBrand": "bmw",
        "brand": "BMW",
        "models": [
            ["bmw-alpina", "ALPINA", "bmw-alpina"],
            ["i3", "i3", "i3"],
            ["", "i4", "i4"],
            ["", "i7", "i7"],
            ["ix3", "IX3", "ix3"],
            ["bmw-i8", "i8", "bmw-i8"],
            ["bmw-m2", "M2", "bmw-m2"],
            ["bmw-m4", "M4", "bmw-m4"],
            ["bmw-x3m", "X3M", "bmw-x3m"],
            ["bmw-x4m", "X4M", "bmw-x4m"],
            ["bmw-x5m", "X5M", "bmw-x5m"],
            ["bmw-x6m", "X6M", "bmw-x6m"],
            ["bmw-z3m", "Z3M", "bmw-z3m"],
            ["bmw-z4m", "Z4M", "bmw-z4m"],
            ["ix", "IX", "ix"],
            ["m1", "M1", "bmw-m1"],
            ["m3", "M3", "bmw-m3"],
            ["m5", "M5", "bmw-m5"],
            ["m6", "M6", "bmw-m6"],
            ["m7", "M7", "bmw-m7"],
            ["m8-", "M8", "m8"],
            ["seria-2", "Series 2", "seria-2"],
            ["seria-4", "Series 4", "seria-4"],
            ["seria-8", "Series 8", "seria-8"],
            ["1-es-sorozat", "Series 1", "seria-1"],
            ["3-as-sorozat", "Series 3", "seria-3"],
            ["5-os-sorozat", "Series 5", "seria-5"],
            ["6-os-sorozat", "Series 6", "seria-6"],
            ["7-es-sorozat", "Series 7", "seria-7"],
            ["x1", "X1", "x1"],
            ["x2", "X2", "x2"],
            ["x3", "X3", "x3"],
            ["x4", "X4", "x4"],
            ["x5", "X5", "x5"],
            ["x6", "X6", "x6"],
            ["x7", "X7", "x-7"],
            ["x8", "X8", ""],
            ["", "XM", "xm"],
            ["z1", "Z1", "bmw-z1"],
            ["z3", "Z3", "bmw-z3"],
            ["z4", "Z4", "bmw-z4"],
            ["z8", "Z8", "bmw-z8"],
        ]
    },
    {
        "olxBrand": "bugatti",
        "brand": "Bugatti",
        "models": [
            ["chiron", "Chiron", "chiron"],
            ["eb-110", "EB 110", "eb-110"],
            ["veyron", "Veyron", "veyron"],
        ]
    },
    {
        "olxBrand": "cadillac",
        "brand": "Cadillac",
        "models": [
            ["allante", "Allante", "allante"],
            ["ats", "ATS", "ats"],
            ["bls", "BLS", "bls"],
            ["brougham", "Brougham", "brougham"],
            ["cimarron", "Cimarron", "cimarron"],
            ["", "CT5", "ct5"],
            ["ct6", "CT6", "ct6"],
            ["", "CTS", "cts"],
            ["deville", "Deville", "deville"],
            ["dts", "DTS", "dts"],
            ["eldorado", "Eldorado", "eldorado"],
            ["escalade", "Escalade", "escalade"],
            ["fleetwood", "Fleetwood", "fleetwood"],
            ["srx", "SRX", "srx"],
            ["seville", "Seville", "seville"],
            ["sts", "STS", "sts"],
            ["xt4", "XT4", "xl4"],
            ["xt5", "XT5", "xt5"],
            ["xt6", "XT6", "xt6"],
            ["xts", "XTS", "xts"],
            ["xlr", "XLR", "xlr"],
        ]
    },
    {
        "olxBrand": "chevrolet",
        "brand": "Chevrolet",
        "models": [
            ["alero", "Alero", "alero"],
            ["apache", "Apache", ""],
            ["astro", "Astro", "astro"],
            ["aveo", "Aveo", "aveo"],
            ["avalanche", "Avalanche", "avalanche"],
            ["beretta", "Beretta", "beretta"],
            ["blazer", "Blazer", "blazer"],
            ["captiva", "Captiva", ""],
            ["camaro", "Camaro", "camaro"],
            ["caprice", "Caprice", "caprice"],
            ["", "Captiva", "captiva"],
            ["cavalier", "Cavalier", "cavalier"],
            ["celebrity", "Celebrity", ""],
            ["chevelle", "Chevelle", "chevelle"],
            ["chevy-van", "Chevy Van", "chevy-van"],
            ["citation", "Citation", ""],
            ["cobalt", "Cobalt", ""],
            ["colorado", "Colorado", "colorado"],
            ["corsica", "Corsica", "corsica"],
            ["corvette", "Corvette", "corvette"],
            ["c-10", "C 10", ""],
            ["c-20", "C 20", ""],
            ["c-30", "C 30", ""],
            ["ct6", "CT6", ""],
            ["cruze", "Cruze", "cruze"],
            ["ct6", "CT6", ""],
            ["el-camino", "El Camino", "el-camino"],
            ["eldorado", "Eldorado", ""],
            ["equinox", "Equinox", "equinox"],
            ["epica", "Epica", "epica"],
            ["escalade", "Escalade", ""],
            ["express", "Express", "express"],
            ["evanda", "Evanda", "evanda"],
            ["fleetwood", "Fleetwood", ""],
            ["g", "G", "g_classe"],
            ["hhr", "HHR", "hhr"],
            ["impala", "Impala", "impala"],
            ["k1500", "K1500", ""],
            ["k30", "K30", ""],
            ["kalos", "Kalos", "kalos"],
            ["lacetti", "Lacetti", "lacetti"],
            ["lumina", "Lumina", "lumina"],
            ["malibu", "Malibu", "malibu"],
            ["matiz", "Matiz", "matiz"],
            ["monza", "Monza", ""],
            ["monte-carlo", "Monte Carlo", ""],
            ["nova", "Nova", ""],
            ["nubira", "Nubira", "nubira"],
            ["orlando", "Orlando", "orlando"],
            ["rezzo", "Rezzo", "rezzo"],
            ["s-10", "S 10", "s-10"],
            ["", "Silverado", "silverado"],
            ["spectrum", "Spectrum", "spectrum"],
            ["spark", "Spark", "spark"],
            ["ssr", "SSR", "ssr"],
            ["suburban", "Suburban", "suburban"],
            ["tacuma", "Tacuma", "tacuma"],
            ["tahoe", "Tahoe", "tahoe"],
            ["trailblazer", "Trailblazer", "trailblazer"],
            ["trans-sport", "Trans Sport", "trans-sport"],
            ["traverse", "Traverse", "traverse"],
            ["2500", "2500", "2500"],
            ["3500", "3500", ""],
            ["1500", "1500", ""],
            ["", "Venture", "venture"],
            ["volt", "Volt", "volt"],
        ]
    },
    {
        "olxBrand": "chrysler",
        "brand": "Chrysler",
        "models": [
            ["300c", "300C", "300c"],
            ["300m", "300M", "300m"],
            ["aspen", "Aspen", "aspen"],
            ["caravan", "Caravan", "caravan"],
            ["concorde", "Concorde", "concorde"],
            ["crossfire", "Crossfire", "crossfire"],
            ["daytona", "Daytona", "daytona"],
            ["es", "ES", "es"],
            ["gts", "GTS", "gts"],
            ["grand-voyager", "Grand Voyager", "grand-voyager"],
            ["gs", "GS", "gs"],
            ["le-baron", "Le Baron", "le-baron"],
            ["lhs", "LHS", "lhs"],
            ["neon", "Neon", "neon"],
            ["new-yorker", "New Yorker", "new-yorker"],
            ["pacifica", "Pacifica", "pacifica"],
            ["pt-cruiser", "PT Cruiser", "pt-cruiser"],
            ["prowler", "Prowler", "prowler"],
            ["sebring", "Sebring", "sebring"],
            ["stratus", "Stratus", "stratus"],
            ["saratoga", "Saratoga", "saratoga"],
            ["town-country", "Town Country", "town-country"],
            ["valiant", "Valiant", "valiant"],
            ["viper", "Viper", "viper"],
            ["vision", "Vision", "vision"],
            ["voyager", "Voyager", "voyager"],
        ]
    },
    {
        "olxBrand": "citroen",
        "brand": "Citroen",
        "models": [
            ["2-cv", "2 CV", "2-cv"],
            ["ax", "AX", "ax"],
            ["axel", "Axel", "axel"],
            ["berlingo", "Berlingo", "berlingo"],
            ["bx", "BX", "bx"],
            ["c1", "C1", "c1"],
            ["c2", "C2", "c2"],
            ["c3", "C3", "c3"],
            ["c3-aircross", "C3 Aircross", "c3-aircross"],
            ["c3-picasso", "C3 Picasso", "c3-picasso"],
            ["c3-pluriel", "C3 Pluriel", "c3-pluriel"],
            ["c4", "C4", "c4"],
            ["c4-aircross", "C4 Aircross", "c4-aircross"],
            ["c4-cactus", "C4 Cactus", "c4-cactus"],
            ["c4-grand-picasso", "Grand C4 Picasso", "c4-grand-picasso"],
            ["c4-grand-picasso-tourer", "Grand C4 Picasso Tourer", "yes"],
            ["c4-picasso", "C4 Picasso", "c4-picasso"],
            ["c4-space-tourer", "C4 Space Tourer", "c4-space-tourer"],
            ["c4x", "C4X", "c4x"],
            ["c5", "C5", "c5"],
            ["c5-aircross", "C5 Aircross", "c5-aircross"],
            ["c6", "C6", "c6"],
            ["c8", "C8", "c8"],
            ["c-crosser", "C Crosser", "c-crosser"],
            ["c-elyse", "C Elyse", "c-elyse"],
            ["c-zero", "C Zero", "c-zero"],
            ["cx", "CX", "cx"],
            ["ds", "DS", "ds"],
            ["ds3", "DS3", "ds3"],
            ["ds4", "DS4", "ds4"],
            ["ds5", "DS5", "ds5"],
            ["ds7", "DS7", "ds7"],
            ["evasion", "Evasion", "evasion"],
            ["gsa", "GSA", "gsa"],
            ["jumper", "Jumper", "jumper"],
            ["jumpy-combi", "Jumpy", "jumpy-combi"],
            ["nemo", "Nemo", "nemo"],
            ["sm", "SM", "sm"],
            ["spacetourer", "Spacetourer", "spacetourer"],
            ["saxo", "Saxo", "saxo"],
            ["", "Visa", "visa"],
            ["xantia", "Xantia", "xantia"],
            ["xm", "XM", "xm"],
            ["xsara", "Xsara", "xsara"],
            ["xsara-picasso", "Xsara Picasso", "xsara-picasso"],
            ["zx", "ZX", "zx"],
        ]
    },
    {
        "olxBrand": "dacia",
        "brand": "Dacia",
        "models": [
            ["1100", "1100", "1100"],
            ["1300", "1300", "1300"],
            ["", "1310", "1310"],
            ["1400", "1400", "1400"],
            ["1410", "1410", "1410"],
            ["dacia-logan-stepway", "Dacia Logan Stepway", "dacia-logan-stepway"],
            ["dokker", "Dokker", "dokker"],
            ["duster", "Duster", "duster"], 
            ["jogger", "Jogger", "jogger"],
            ["logan", "logan", "logan"], 
            ["logan-van", "Logan Van", "logan-van"],
            ["lodgy", "Lodgy", "lodgy"],
            ["nova", "Nova", "nova"],
            ["pick-up", "Pick Up", "pick-up"],
            ["sandero", "Sandero", "sandero"],
            ["sandero-stepway", "Sandero Stepway", "sandero-stepway"], 
            ["solenza", "Solenza", "solenza"],
            ["spring", "Spring", "spring"],
            ["super-nova", "Super Nova", "super-nova"],
        ]
    },
    {
        "olxBrand": "daewoo",
        "brand": "Daewoo",
        "models": [
            ["chairman", "Chairman", "chairman"],
            ["cielo", "Cielo", "cielo"],
            ["espero", "Espero", "espero"],
            ["evanda", "Evanda", "evanda"],
            ["kalos", "Kalos", "kalos"],
            ["korando", "Korando", "korando"],
            ["lacetti", "Lacetti", "lacetti"],
            ["lanos", "Lanos", "lanos"],
            ["leganza", "Leganza", "leganza"],
            ["matiz", "Matiz", "matiz"],
            ["musso", "Musso", "musso"],
            ["nexia", "Nexia", "nexia"],
            ["nubira", "Nubira", "nubira"],
            ["racer", "Racer", "racer"],
            ["rezzo", "Rezzo", "rezzo"],
            ["tacuma", "Tacuma", "tacuma"],
            ["tico", "Tico", "tico"],
        ]
    },
    {
        "olxBrand": "daihatsu",
        "brand": "Daihatsu",
        "models": [
            ["applause", "Applause", "applause"],
            ["charade", "Charade", "charade"],
            ["charmant", "Charmant", "charmant"],
            ["copen", "Copen", "copen"],
            ["cuore", "Cuore", "cuore"],
            ["feroza", "Feroza", "feroza"],
            ["fourtrak", "Fourtrak", "fourtrak"],
            ["freeclimber", "Freeclimber", "freeclimber"],
            ["gran-move", "Gran Move", "gran-move"],
            ["hijet", "Hijet", "hijet"],
            ["materia", "Materia", "materia"],
            ["more", "Move", "move"],
            ["rocky", "Rocky", "rocky"],
            ["sirion", "Sirion", "sirion"],
            ["sportrak", "Sportrak", "sportrak"],
            ["terios", "Terios", "terios"],
            ["trevis", "Trevis", "trevis"],
            ["yrv", "YRV", "yrv"],
        ]
    },
    {
        "olxBrand": "dodge",
        "brand": "Dodge",
        "models": [
            ["avenger", "Avenger", "avenger"],
            ["caliber", "Caliber", "caliber"],
            ["caravan", "Caravan", "caravan"],
            ["charger", "Charger", "charger"],
            ["challenger", "Challenger", "challenger"],
            ["dart", "Dart", "dart"],
            ["", "Dakota", "dakota"],
            ["daytona", "Daytona", "daytona"],
            ["diplomat", "Diplomat", "diplomat"],
            ["durango", "Durango", "durango"],
            ["dynasty", "Dynasty", "dynasty"],
            ["grand-caravan", "Grand Caravan", "grand-caravan"],
            ["hornet", "Hornet", "hornet"],
            ["intrepid", "Intrepid", "intrepid"],
            ["journey", "Journey", "journey"],
            ["magnum", "Magnum", "magnum"],
            ["monaco", "Monaco", "monaco"],
            ["neon", "Neon", "neon"],
            ["nitro", "Nitro", "nitro"],
            ["omni", "Omni", "omni"],
            ["ram", "Ram", "ram"],
            ["spirit", "Spirit", "spirit"],
            ["stealth", "Stealth", "stealth"],
            ["stratus", "Stratus", "stratus"],
            ["viper", "Viper", "viper"],
        ]
    },
    {
        "olxBrand": "ferrari",
        "brand": "Ferrari",
        "models": [
            ["208-308", "208-308", "208-308"],
            ["308", "308", ""],
            ["328", "328", "328"],
            ["348", "348", "348"],
            ["360", "360", "360"],
            ["365", "365", ""],
            ["400", "400", "400"],
            ["412", "412", "412"],
            ["456", "456", "456"],
            ["512", "512", "512"],
            ["550-", "550", "550-"],
            ["575", "575", "575"],
            ["599GTB", "599 GTB", "yes"],
            ["599-gto", "599 GTO", "599-gto"],
            ["612", "612", "612"],
            ["812", "812", "812-superfast"],
            ["california", "California", "california"],
            ["", "Dino", "dino-gt4"],
            ["", "Enzo", "enzo"],
            ["", "F12", "f12berlinetta"],
            ["458-italia", "F458 Italia", "458-italia"],
            ["488-gtb", "F488 GTB", "488-gtb"],
            ["488-spider", "F488 Spider", "488-spider"],
            ["roma-", "Roma", "roma-"],
            ["f8-", "F8", "f8-"],
            ["", "F355", "f355"], 
            ["", "F40", "f40"], 
            ["", "F430", "f430"], 
            ["", "F50", "f50"], 
            ["", "FF", "ff"], 
            ["", "FXX", "fxx"], 
            ["gtc4lussot", "GTC4 Lusso T", "gtc4lussot"],
            ["", "LaFerrari", "laferrari"],
            ["", "Mondial", "mondial"],
            ["portofino", "Portofino", "portofino"],
            ["", "Purosangue", "purosangue"],
            ["", "SF90 Stradale", "sf90-stradale"],
            ["", "Superamerica", "superamerica"],
            ["", "Testarossa", "testarossa"]
        ]
    },
    {
        "olxBrand": "fiat",
        "brand": "Fiat",
        "models": [
            ["124", "124", "124"],
            ["125p", "125p", "125p"],
            ["", "126", "126"],
            ["127", "127", "127"],
            ["128", "128", "128"],
            ["", "130", "130"],
            ["131", "131", "131"],
            ["132", "132", "132"],
            ["600", "600", "600"],
            ["850", "850", "850"],
            ["ducato", "Ducato", "ducato"],
            ["palio", "Palio", "palio"],
            ["ritmo", "Ritmo", "ritmo"],
            ["sedici", "Sedici", "sedici"],
            ["seicento", "Seicento", "seicento"],
            ["stilo", "Stilo", "stilo"],
            ["tempra", "Tempra", "tempra"],
            ["tipo", "Tipo", "tipo"],
            ["ulysse", "Ulysse", "ulysse"],
            ["x-1-9", "X1/9", "x-1"],
            ["500", "500", "500"],
            ["500l", "500l", "500l"],
            ["500x", "500x", "500x"],
            ["albea", "Albea", "albea"],
            ["barchetta", "Barchetta", "barchetta"],
            ["brava", "Brava", "brava"],
            ["bravo", "Bravo", "bravo"],
            ["cinquecento", "Cinquecento", "cinquecento"],
            ["coupe", "Coupe", "coupe"],
            ["doblo", "Doblo", "doblo"],
            ["dino", "Dino", "dino"],
            ["freemont", "Freemont", "freemont"],
            ["fullback", "Fullback", "fullback"],
            ["grande-punto", "Grande Punto", "grande-punto"],
            ["idea", "Idea", "idea"],
            ["linea", "Linea", "linea"],
            ["marea", "Marea", "marea"],
            ["multipla", "Multipla", "multipla"],
            ["panda", "Panda", "panda"],
            ["punto", "Punto", "punto"],
            ["punto-evo", "Punto EVO", ""],
            ["qubo", "Qubo", "qubo"],
            ["regata", "Regata", "regata"],
            ["scudo", "Scudo", "scudo"],
            ["spider-europa", "Spider 2000", "spider-europa"],
            ["strada", "Strada", "strada"],
            ["talento", "Talento", "talento"],
        ]
    },
    {
        "olxBrand": "ford",
        "brand": "Ford",
        "models": [
            ['', 'Aerostar', 'aerostar'],
            ['aspire', 'Aspire', 'aspire'],
            ['b-max', 'B Max', 'b-max'],
            ['bronco', 'Bronco', 'bronco'],
            ['capri', 'Capri', 'capri'],
            ['c-max', 'C Max', 'c-max'],
            ['c-max-grand', 'C Max Grand', ''],
            ['contour', 'Contour', 'contour'],
            ['cougar', 'Cougar', 'cougar'],
            ['courier', 'Courier', 'courier'],
            ['crown', 'Crown', 'crown'],
            ['econoline', 'Econoline', 'econoline'],
            ['econovan', 'Econovan', 'econovan'],
            ['ecosport', 'Ecosport', 'ecosport'],
            ['edge', 'Edge', 'edge'],
            ['escape', 'Escape', 'escape'],
            ['escort', 'Escort', 'escort'],
            ['excursion', 'Excursion', 'excursion'],
            ['expedition', 'Expedition', 'expedition'],
            ['explorer', 'Explorer', 'explorer'],
            ['f150', 'F150', 'f150'],
            ['f250', 'F250', 'f250'],
            ['f350', 'F350', 'f350'],
            ['fairlane', 'Fairlane', 'fairlane'],
            ['falcon', 'Falcon', 'falcon'],
            ['festiva', 'Festiva', 'festiva'],
            ['fiesta', 'Fiesta', 'fiesta'],
            ['five-hundred', 'Five Hundred', 'five-hundred'],
            ['focus', 'Focus', 'focus'],
            ['focus-c-max', 'Focus C Max', 'focus-c-max'],
            ['freestar', 'Freestar', 'freestar'],
            ['freestyle', 'Freestyle', 'freestyle'],
            ['fusion', 'Fusion', 'fusion'],
            ['galaxy', 'Galaxy', 'galaxy'],
            ['granada', 'Granada', 'granada'],
            ['grand-c-max', 'Grand C Max', 'grand-c-max'],
            ['gt', 'GT', 'gt'],
            ['ka', 'Ka', 'ka'],
            ['ka-plus', 'Ka Plus', 'ka-plus'],
            ['kuga', 'Kuga', 'kuga'],
            ['maverick', 'Maverick', 'maverick'],
            ['mercury', 'Mercury', 'mercury'],
            ['mondeo', 'Mondeo', 'mondeo'],
            ['mustang', 'Mustang', 'mustang'],
            ['mustang-mach-e', 'Mustang Mach E', 'mustang-mach-e'],
            ['orion', 'Orion', 'orion'],
            ['probe', 'Probe', 'probe'],
            ['puma', 'Puma', 'puma'],
            ['ranger', 'Ranger', 'ranger'],
            ['raptor', 'Raptor', 'raptor'],
            ['ranchero', 'Ranchero', ''],
            ['s-max', 'S Max', 's-max'],
            ['scorpio', 'Scorpio', 'scorpio'],
            ['sierra', 'Sierra', 'sierra'],
            ['streetka', 'Streetka', 'streetka'],
            ['taunus', 'Taunus', 'taunus'],
            ['taurus', 'Taurus', 'taurus'],
            ['tempo', 'Tempo', 'tempo'],
            ['thunderbird', 'Thunderbird', 'thunderbird'],
            ['tourneo', 'Tourneo', 'tourneo'],
            ['tourneo-connect', 'Tourneo Connect', 'tourneo-connect'],
            ['tourneo-courier', 'Tourneo Courier', 'tourneo-courier'],
            ['tourneo-custom-', 'Tourneo Custom', 'tourneo-custom-'],
            ['transit', 'Transit', 'transit'],
            ['transit-connect', 'Transit Connect', 'transit-connect'],
            ['transit-custom-', 'Transit Custom', 'transit-custom-'],
            ['windstar', 'Windstar', 'windstar'],
        ],
    },
    {
        "olxBrand": "honda",
        "brand": "Honda",
        "models": [
            ['accord', 'Accord', 'accord'],
            ['aerodeck', 'Aerodeck', 'aerodeck'],
            ['city', 'City', 'city'],
            ['civic', 'Civic', 'civic'],
            ['concerto', 'Concerto', 'concerto'],
            ['cr-v', 'CR-V', 'cr-v'],
            ['cr-z', 'CR-Z', 'cr-z'],
            ['crx', 'CRX', 'crx'],
            ['element', 'Element', 'element'],
            ['', 'ENS1', 'ens1'],
            ['fr-v', 'FR-V', 'fr-v'],
            ['honda-e', 'Honda E', 'honda-e'],
            ['hr-v', 'HR-V', 'hr-v'],
            ['insight', 'Insight', 'insight'],
            ['integra', 'Integra', 'integra'],
            ['jazz', 'Jazz', 'jazz'],
            ['legend', 'Legend', 'legend'],
            ['logo', 'Logo', 'logo'],
            ['nsx', 'NSX', 'nsx'],
            ['odyssey', 'Odyssey', 'odyssey'],
            ['pilot', 'Pilot', 'pilot'],
            ['prelude', 'Prelude', 'prelude'],
            ['ridgeline', 'Ridgeline', 'ridgeline'],
            ['s-2000', 'S-2000', 's-2000'],
            ['shuttle', 'Shuttle', 'shuttle'],
            ['stream', 'Stream', 'stream'],
        ],
    },
    {
        "olxBrand": "hummer",
        "brand": "Hummer",
        "models": [
            ["h1", "H1", "h1"],
            ["h2", "H2", "h2"],
            ["h3", "H3", "h3"],
        ],
    },
    {
        "olxBrand": "hyundai",
        "brand": "Hyundai",
        "models": [
            ['accent', 'Accent', 'accent'],
            ['atos', 'Atos', 'atos'],
            ['avante', 'Avante', 'avante'],
            ['azera', 'Azera', 'azera'],
            ['Bayon', 'Bayon', 'bayon'],
            ['coupe', 'Coupe', 'coupe'],
            ['elantra', 'Elantra', 'elantra'],
            ['equus', 'Equus', ''],
            ['excel', 'Excel', 'excel'],
            ['galloper', 'Galloper', 'galloper'],
            ['genesis', 'Genesis', 'genesis'],
            ['genesis-coupe', 'Genesis Coupe', ''],
            ['getz', 'Getz', 'getz'],
            ['grand-santa-fe', 'Grand Santa Fe', 'grand-santa-fe'],
            ['grandeur', 'Grandeur', 'grandeur'],
            ['h-1', 'H-1', 'h-1'],
            ['h-1-starex', 'H-1 Starex', 'h-1-starex'],
            ['h200', 'H200', 'h200'],
            ['h350', 'H350', 'h350'],
            ['i10', 'i10', 'i10'],
            ['i20', 'i20', 'i20'],
            ['i25', 'i25', ''],
            ['i30', 'i30', 'i30'],
            ['i40', 'i40', 'i40'],
            ['ioniq', 'Ioniq', 'ioniq'],
            ['ix20', 'ix20', 'ix20'],
            ['ix35', 'ix35', 'ix35'],
            ['ix55', 'ix55', 'ix55'],
            ['kona', 'Kona', 'kona'],
            ['lantra', 'Lantra', 'lantra'],
            ['lavita', 'Lavita', 'lavita'],
            ['matrix', 'Matrix', 'matrix'],
            ['pony', 'Pony', 'pony'],
            ['s-coupe', 'S Coupe', 's-coupe'],
            ['santa-fe', 'Santa Fe', 'santa-fe'],
            ['santamo', 'Santamo', 'santamo'],
            ['sonata', 'Sonata', 'sonata'],
            ['sonica', 'Sonica', 'no'],
            ['', 'Staria', 'staria'],
            ['terracan', 'Terracan', 'terracan'],
            ['trajet', 'Trajet', 'trajet'],
            ['tucson', 'Tucson', 'tucson'],
            ['veloster', 'Veloster', 'veloster'],
            ['veracruz', 'Veracruz', 'veracruz'],
            ['xg', 'XG', 'xg'],
            ['xg-30', 'XG 30', ''],
            ['xg-350', 'XG 350', ''],
        ],
    },
    {
        "olxBrand": "infiniti",
        "brand": "Infiniti",
        "models": [
            ['ex', 'EX', 'yes'],
            ['ex-30', 'EX 30', 'yes'],
            ['ex-35', 'EX 35', 'yes'],
            ['ex-37', 'EX 37', 'yes'],
            ['fx-35', 'FX 35', 'yes'],
            ['fx-37', 'FX 37', 'yes'],
            ['fx-45', 'FX 45', 'yes'],
            ['fx-50', 'FX 50', 'yes'],
            ['fx30d', 'FX 30', 'yes'],
            ['g20', 'G20', 'yes'],
            ['g35', 'G35', 'yes'],
            ['g37', 'G37', 'yes'],
            ['i35', 'I35', 'no'],
            ['j30', 'J30', 'no'],
            ['m30d', 'M30', 'yes'],
            ['m35', 'M35', 'yes'],
            ['m37', 'M37', 'yes'],
            ['q30', 'Q30', 'yes'],
            ['q45', 'Q45', 'yes'],
            ['q50', 'Q50', 'yes'],
            ['q60', 'Q60', 'yes'],
            ['q70', 'Q70', 'yes'],
            ['qx30', 'QX30', 'yes'],
            ['qx50', 'QX50', 'yes'],
            ['qx56', 'QX56', 'yes'],
            ['qx70', 'QX70', 'yes'],
            ['qx80', 'QX80', 'yes'],
        ],
    },
    {
        "olxBrand": "jaguar",
        "brand": "Jaguar",
        "models": [
            ['daimler', 'Daimler', 'yes'],
            ['e-pace', 'E-Pace', 'yes'],
            ['e-type', 'E-Type', 'yes'],
            ['f-pace', 'F-Pace', 'yes'],
            ['f-type', 'F-Type', 'yes'],
            ['i-pace', 'I-Pace', 'yes'],
            ['mk-ii', 'MK II', 'no'],
            ['s-type', 'S-Type', 'yes'],
            ['s-type-r', 'S-Type R', 'no'],
            ['x-type', 'X-Type', 'yes'],
            ['xj', 'XJ', 'yes'],
            ['xj12', 'XJ12', 'no'],
            ['xe', 'XE', 'yes'],
            ['xf', 'XF', 'yes'],
        ],
    },
    {
        "olxBrand": "jeep",
        "brand": "Jeep",
        "models": [
            ['cherokee', 'Cherokee', 'yes'],
            ['cj', 'CJ', 'no'],
            ['comanche', 'Comanche', 'no'],
            ['commander', 'Commander', 'yes'],
            ['compass', 'Compass', 'yes'],
            ['Gladiator', 'Gladiator', 'no'],
            ['grand-cherokee', 'Grand Cherokee', 'yes'],
            ['liberty', 'Liberty', 'no'],
            ['patriot', 'Patriot', 'yes'],
            ['renegade', 'Renegade', 'yes'],
            ['wrangler', 'Wrangler', 'yes'],
            ['wagoneer', 'Wagoneer', 'no'],
            ['willys', 'Willys', 'no'],
        ],
    },
    {
        "olxBrand": "kia",
        "brand": "Kia",
        "models": [
            ['asia-rocsta', 'Asia Rocsta', 'no'],
            ['besta', 'Besta', 'yes'],
            ['carens', 'Carens', 'yes'],
            ['carnival', 'Carnival', 'yes'],
            ['cerato', 'Cerato', 'yes'],
            ['ceed', 'Ceed', 'yes'],
            ['clarus', 'Clarus', 'yes'],
            ['elan', 'Elan', 'no'],
            ['joice', 'Joice', 'yes'],
            ['leo', 'Leo', 'no'],
            ['magentis', 'Magentis', 'yes'],
            ['mentor', 'Mentor', 'no'],
            ['niro', 'Niro', 'yes'],
            ['opirus', 'Opirus', 'yes'],
            ['optima', 'Optima', 'yes'],
            ['picanto', 'Picanto', 'yes'],
            ['pride', 'Pride', 'yes'],
            ['pregio', 'Pregio', 'yes'],
            ['pro-ceed', 'ProCeed', 'yes'],
            ['retona', 'Retona', 'yes'],
            ['rio', 'Rio', 'yes'],
            ['rocsta', 'Rocsta', 'no'],
            ['roadster', 'Roadster', 'yes'],
            ['sedona', 'Sedona', 'no'],
            ['sephia', 'Sephia', 'yes'],
            ['shuma', 'Shuma', 'yes'],
            ['soul', 'Soul', 'yes'],
            ['sorento', 'Sorento', 'yes'],
            ['spectra', 'Spectra', 'no'],
            ['sportage', 'Sportage', 'yes'],
            ['stinger', 'Stinger', 'yes'],
            ['stonic', 'Stonic', 'yes'],
            ['venga', 'Venga', 'yes'],
            ['xceed', 'XCeed', 'no'],
        ],
    },
    {
        "olxBrand": "lamborghini",
        "brand": "Lamborghini",
        "models": [
            ['aventador', 'Aventador', 'yes'],
            ['countach', 'Countach', 'yes'],
            ['diablo', 'Diablo', 'yes'],
            ['espada', 'Espada', 'yes'],
            ['gallardo', 'Gallardo', 'yes'],
            ['huracan', 'Huracan', 'yes'],
            ['jalpa', 'Jalpa', 'yes'],
            ['lm', 'LM', 'yes'],
            ['miura', 'Miura', 'yes'],
            ['murcielago', 'Murcielago', 'yes'],
            ['Reventon', 'Reventon', 'yes'],
            ['urraco', 'Urraco', 'yes'],
            ['urus', 'Urus', 'yes'],
        ],
    },
    {
        "olxBrand": "land-rover",
        "brand": "Land Rover",
        "models": [
            ['defender', 'Defender', 'yes'],
            ['discovery', 'Discovery', 'yes'],
            ['discovery-sport', 'Discovery Sport', 'yes'],
            ['freelander', 'Freelander', 'yes'], # OLX
            ['range-rover', 'Range Rover', 'yes'], # OLX
            ['range-rover-evoque', 'Range Rover Evoque', 'yes'], # OLX
            ['range-rover-sport', 'Range Rover Sport', 'yes'],
            ['range-rover-velar', 'Range Rover Velar', 'yes'],
            ['range-rover-vogue', 'Range Rover Vogue', 'no'],
        ],
    },
    {
        "olxBrand": "mazda",
        "brand": "Mazda",
        "models": [
            ['121', '121', 'yes'],
            ['2', '2', 'yes'],
            ['3', '3', 'yes'], # OLX
            ['6', '6', 'yes'], # OLX
            ['5', '5', 'yes'],
            ['626', '626', 'yes'],
            ['929', '929', 'yes'],
            ['323', '323', 'yes'],
            ['323f', '323f', 'yes'],
            ['bongo', 'Bongo', 'no'],
            ['bt-50', 'BT-50', 'yes'],
            ['seria-b', 'B Serie', 'yes'],
            ['cx-3', 'CX-3', 'yes'],
            ['cx-5', 'CX-5', 'yes'], # OLX
            ['cx-7', 'CX-7', 'yes'],
            ['cx-9', 'CX-9', 'no'],
            ['cx-30', 'CX-30', 'no'],
            ['demio', 'Demio', 'yes'],
            ['seria-e', 'E Serie', 'yes'],
            ['millenia', 'millenia', 'no'],
            ['mpv', 'MPV', 'yes'],
            ['mx-3', 'MX-3', 'yes'],
            ['mx-5', 'MX-5', 'yes'],
            ['mx-6', 'MX-6', 'yes'],
            ['mx-30', 'MX-30', 'no'],
            ['premacy', 'Premacy', 'yes'],
            ['protege', 'Protege', 'no'],
            ['rx-6', 'RX-6', 'no'],
            ['rx-7', 'RX-7', 'yes'],
            ['rx-8', 'RX-8', 'yes'],
            ['tribute', 'Tribute', 'yes'],
            ['xedos', 'Xedos', 'yes'],
        ],
    },
    {
        "olxBrand": "mercedes",
        "brand": "Mercedes",
        "models": [
            ['a-class', 'A', 'yes'], # OLX
            ['amg', 'AMG', 'yes'],
            ['amg-gt-s', 'AMG GT S', 'yes'],
            ['200-seria', '200', 'yes'],
            ['190-seria', '190', 'yes'],
            ['300-seria', '300', 'yes'],
            ['b-class', 'B', 'yes'], # OLX
            ['c-class', 'C', 'yes'], # OLX
            ['ce', 'CE', 'yes'],
            ['clc', 'CLC', 'yes'],
            ['cla', 'CLA', 'yes'], # OLX
            ['clk-class', 'CLK', 'yes'],
            ['cl-class', 'CL', 'yes'],
            ['cls-class', 'CLS', 'yes'],
            ['EQA', 'EQA', 'yes'],
            ['e-class', 'E', 'yes'], # OLX
            ['eqe', 'EQE', 'yes'],
            ['eqb', 'EQB', 'yes'],
            ['eqc', 'EQC', 'yes'],
            ['EQS', 'EQS', 'yes'],
            ['EQV', 'EQV', 'yes'],
            ['gle', 'GLE', 'yes'], # OLX
            ['gle-coupe', 'GLE', 'yes'],
            ['gl-class', 'GL', 'yes'],
            ['gls', 'GLS', 'yes'],
            ['gla', 'GLA', 'yes'], # OLX
            ['glc', 'GLC', 'yes'], # OLX
            ['glb', 'GLB', 'yes'],
            ['glk-class', 'GLK', 'yes'],
            ['g-class', 'G', 'yes'], # OLX
            ['ml-class', 'ML', 'yes'], # OLX
            ['mb-100', 'MB-100', 'yes'],
            ['monarch', 'Monarch', 'yes'],
            ['r-class', 'R', 'yes'],
            ['s-class', 'S', 'yes'], # OLX
            ['slr', 'SLR', 'yes'],
            ['sls', 'SLS', 'yes'],
            ['sl-class', 'SL', 'yes'],
            ['slk', 'SLK', 'yes'],
            ['sprinter', 'Sprinter', 'yes'], # OLX
            ['vaneo', 'Vaneo', 'yes'],
            ['vario', 'Vario', 'yes'],
            ['v', 'V', 'yes'],
            ['vito', 'Vito', 'yes'], # OLX
            ['viano', 'Viano', 'yes'],
            ['w123', 'W123', 'yes'],
            ['w124', 'W124', 'yes'],
            ['x', 'X', 'yes'],
        ],
    },
    {
        "olxBrand": "mini",
        "brand": "Mini",
        "models": [
            ["Clubman", "Clubman", "no"],
            ["Cooper", "Cooper", "no"], # OLX
            ["cooper-s", "Cooper S", "no"],
            ["cooper-se", "Cooper SE", "no"],
            ["countryman", "Countryman", "no"],
            ["one", "One", "no"],
            ["paceman", "Paceman", "no"],
            ["roadster", "Roadster", "no"],
        ],
    },
    {
        "olxBrand": "mitsubishi",
        "brand": "Mitsubishi",
        "models": [
            ['asx', 'ASX', 'yes'],
            ['canter', 'Canter', 'no'],
            ['carisma', 'Carisma', 'yes'],
            ['colt', 'Colt', 'yes'],
            ['cordia', 'Cordia', 'yes'],
            ['3000-gt', '3000 GT', 'yes'],
            ['cosmos', 'Cosmos', 'no'],
            ['diamante', 'Diamante', 'no'],
            ['eclipse', 'Eclipse', 'yes'],
            ['eclipse-cross', 'Eclipse Cross', 'yes'],
            ['endeavor', 'Endeavor', 'no'],
            ['fto', 'FTO', 'no'],
            ['galloper', 'Galloper', 'no'],
            ['galant', 'Galant', 'yes'],
            ['grandis', 'Grandis', 'yes'],
            ['i-miev', 'I-MIEV', 'no'],
            ['l200', 'L200', 'yes'],
            ['l300', 'L300', 'yes'],
            ['l400', 'L400', 'yes'],
            ['lancer', 'lancer', 'yes'],
            ['lancer-evolution', 'Lancer Evolution', 'no'],
            ['lancer-evolution-vii', 'Lancer Evolution VII', 'no'],
            ['lancer-evolution-viii', 'Lancer Evolution VIII', 'yes'],
            ['lancer-evolution-ix', 'Lancer Evolution IX', 'yes'],
            ['lancer-evolution-x', 'Lancer Evolution X', 'yes'],
            ['mirage', 'Mirage', 'no'],
            ['montero', 'Montero', 'no'],
            ['outlander', 'Outlander', 'yes'],
            ['pajero', 'Pajero', 'yes'],
            ['pajero-pinin', 'Pajero Pinin', 'yes'],
            ['santamo', 'Santamo', 'no'],
            ['sapporo', 'Sapporo', 'yes'],
            ['sigma', 'Sigma', 'yes'],
            ['space-gear', 'Space Gear', 'yes'],
            ['space-runner', 'Space Runner', 'yes'],
            ['space-star', 'Space Star', 'yes'],
            ['space-wagon', 'Space Wagon', 'yes'],
            ['starion', 'Starion', 'yes'],
            ['tredia', 'Tredia', 'yes'],
        ],
    },
    {
        "olxBrand": "nissan",
        "brand": "Nissan",
        "models": [
            ['100-nx', '100 NX', 'yes'],
            ['200-sx', '200 SX', 'yes'],
            ['240-sx', '240-SX', 'no'],
            ['280-zx', '280-ZX', 'no'],
            ['300-zx', '300 ZX', 'yes'],
            ['350-z', '350Z', 'yes'],
            ['370-z', '370Z', 'yes'],
            ['almera', 'Almera', 'yes'],
            ['almera-tino', 'Almera Tino', 'yes'],
            ['altima', 'Altima', 'no'],
            ['armada', 'Armada', 'no'],
            ['bluebird', 'Bluebird', 'yes'],
            ['cherry', 'Cherry', 'yes'],
            ['cube', 'Cube', 'yes'],
            ['evalia', 'Evalia', 'yes'],
            ['frontier', 'Frontier', 'no'],
            ['gt-r', 'GT-R', 'yes'],
            ['interstar', 'Interstar', 'yes'],
            ['juke', 'Juke', 'yes'],
            ['king-cab', 'King Cab', 'no'],
            ['kubistar', 'Kubistar', 'yes'],
            ['laurel', 'Laurel', 'no'],
            ['leaf', 'Leaf', 'yes'],
            ['maxima', 'Maxima', 'yes'],
            ['micra', 'Micra', 'yes'],
            ['murano', 'Murano', 'yes'],
            ['navara', 'Navara', 'yes'],
            ['new-micra', 'New Micra', 'no'],
            ['note', 'Note', 'yes'],
            ['nv200', 'NV200', 'yes'],
            ['pathfinder', 'Pathfinder', 'yes'],
            ['patrol', 'Patrol', 'yes'],
            ['pickup', 'Pickup', 'yes'],
            ['pixo', 'Pixo', 'yes'],
            ['primastar', 'Primastar', 'yes'],
            ['primera', 'Primera', 'yes'],
            ['prairie', 'Prairie', 'yes'],
            ['pulsar', 'Pulsar', 'yes'],
            ['qashqai', 'Qashqai', 'yes'],
            ['qashqai-2', 'Qashqai 2', 'yes'],
            ['quest', 'Quest', 'no'],
            ['rogue', 'Rogue', 'no'],
            ['sentra', 'Sentra', 'no'],
            ['serena', 'Serena', 'yes'],
            ['silvia', 'Silvia', 'no'],
            ['skyline', 'Skyline', 'no'],
            ['stanza', 'Stanza', 'no'],
            ['sunny', 'Sunny', 'yes'],
            ['terrano', 'Terrano', 'yes'],
            ['tiida', 'Tiida', 'yes'],
            ['titan', 'Titan', 'no'],
            ['trade', 'Trade', 'no'],
            ['urvan', 'Urvan', 'no'],
            ['vanette', 'Vanette', 'yes'],
            ['x-trail', 'X-Trail', 'yes'],
            ['xterra', 'Xterra', 'no'],
        ],
    },
    {
        "olxBrand": "opel",
        "brand": "Opel",
        "models": [
            ['adam', 'Adam', 'yes'],
            ['agila', 'Agila', 'yes'],
            ['ampera', 'Ampera', 'yes'],
            ['ampera-e', 'Ampera-E', 'yes'],
            ['antara', 'Antara', 'yes'],
            ['arena', 'Arena', 'yes'],
            ['ascona', 'Ascona', 'yes'],
            ['astra', 'Astra', 'yes'],
            ['calibra', 'Calibra', 'yes'],
            ['campo', 'Campo', 'yes'],
            ['cascada', 'Cascada', 'yes'],
            ['combo', 'Combo', 'yes'],
            ['commodore', 'Commodore', 'yes'],
            ['corsa', 'Corsa', 'yes'],
            ['crossland-x', 'Crossland-X', 'yes'],
            ['diplomat', 'Diplomat', 'yes'],
            ['frontera', 'Frontera', 'yes'],
            ['grandland', 'Grandland', 'no'],
            ['grandland-x', 'Grandland X', 'yes'],
            ['gt', 'GT', 'yes'],
            ['insignia', 'Insignia', 'yes'],
            ['kadett', 'Kadett', 'yes'],
            ['karl', 'Karl', 'yes'],
            ['manta', 'Manta', 'yes'],
            ['meriva', 'Meriva', 'yes'],
            ['mokka', 'Mokka', 'yes'],
            ['monterey', 'Monterey', 'yes'],
            ['monza', 'Monza', 'yes'],
            ['movano', 'Movano', 'yes'],
            ['nova', 'Nova', 'no'],
            ['omega', 'Omega', 'yes'],
            ['rekord', 'Rekord', 'yes'],
            ['senator', 'Senator', 'yes'],
            ['signum', 'Signum', 'yes'],
            ['sintra', 'Sintra', 'yes'],
            ['speedster', 'Speedster', 'yes'],
            ['tigra', 'Tigra', 'yes'],
            ['vectra', 'Vectra', 'yes'],
            ['vivaro', 'Vivaro', 'yes'],
            ['zafira', 'Zafira', 'yes'],
        ],
    },
    {
        "olxBrand": "peugeot",
        "brand": "Peugeot",
        "models": [
            ['104', '104', 'yes'],
            ['106', '106', 'yes'],
            ['107', '107', 'yes'],
            ['108', '108', 'yes'],
            ['1007', '1007', 'yes'],
            ['2008', '2008', 'yes'],
            ['204', '204', 'no'],
            ['205', '205', 'yes'],
            ['206', '206', 'yes'],
            ['206-cc', '206 CC', 'yes'],
            ['206-plus', '206 Plus', 'no'],
            ['207', '207', 'yes'],
            ['207-cc', '207 CC', 'yes'],
            ['208', '208', 'yes'],
            ['3008', '3008', 'yes'],
            ['301', '301', 'no'],
            ['304', '304', 'yes'],
            ['305', '305', 'yes'],
            ['306', '306', 'yes'],
            ['307', '307', 'yes'],
            ['307-cc', '307 CC', 'yes'],
            ['307-sw', '307 SW', 'yes'],
            ['308', '308', 'yes'],
            ['309', '309', 'yes'],
            ['395', '395', 'no'],
            ['4007', '4007', 'yes'],
            ['4008', '4008', 'yes'],
            ['404', '404', 'no'],
            ['405', '405', 'yes'],
            ['406', '406', 'yes'],
            ['407', '407', 'yes'],
            ['408', '408', 'no'],
            ['5008', '5008', 'yes'],
            ['504', '504', 'yes'],
            ['505', '505', 'yes'],
            ['508', '508', 'yes'],
            ['604', '604', 'yes'],
            ['605', '605', 'yes'],
            ['607', '607', 'yes'],
            ['806', '806', 'yes'],
            ['807', '807', 'yes'],
            ['bipper', 'Bipper', 'yes'],
            ['boxer', 'Boxer', 'yes'],
            ['expert', 'Expert', 'yes'],
            ['ion', 'IOn', 'yes'],
            ['partner', 'Partner', 'yes'],
            ['rcz', 'RCZ', 'yes'],
            ['rifter', 'Rifter', 'yes'],
            ['traveller', 'Traveller', 'yes'],
        ],
    },
    {
        "olxBrand": "porsche",
        "brand": "Porsche",
        "models": [
            ['356', '356', 'yes'],
            ['911', '911', 'yes'],
            ['911-turbo-s', '911 Turbo S', 'no'],
            ['912', '912', 'yes'],
            ['914', '914', 'yes'],
            ['924', '924', 'yes'],
            ['928', '928', 'yes'],
            ['944', '944', 'yes'],
            ['959', '959', 'yes'],
            ['962', '962', 'no'],
            ['968', '968', 'yes'],
            ['boxster', 'Boxster', 'yes'],
            ['carrera-gt', 'Carrera GT', 'yes'],
            ['cayenne', 'Cayenne', 'yes'],
            ['cayenne-gts', 'Cayenne GTS', 'no'],
            ['cayenne-s', 'Cayenne S', 'no'],
            ['cayenne-turbo', 'Cayenne Turbo', 'no'],
            ['cayman', 'Cayman', 'yes'],
            ['macan', 'Macan', 'yes'],
            ['panamera', 'Panamera', 'yes'],
            ['taycan', 'Taycan', 'no'],
        ],
    },
    {
        "olxBrand": "renault",
        "brand": "Renault",
        "models": [
            ['4', '4', 'no'],
            ['5', '5', 'no'],
            ['8', '8', 'no'],
            ['9', '9', 'no'],
            ['10', '10', 'no'],
            ['11', '11', 'no'],
            ['12', '12', 'no'],
            ['14', '14', 'no'],
            ['16', '16', 'no'],
            ['18', '18', 'no'],
            ['19', '19', 'no'],
            ['20', '20', 'no'],
            ['21', '21', 'no'],
            ['25', '25', 'no'],
            ['30', '30', 'no'],
            ['alaskan', 'Alaskan', 'yes'],
            ['alpine-a110', 'Alpine A110', 'no'],
            ['alpine-a310', 'Alpine A310', 'no'],
            ['alpine-v6', 'Alpine V6', 'no'],
            ['arkana', 'Arkana', 'no'],
            ['avantime', 'Avantime', 'yes'],
            ['captur', 'Captur', 'yes'],
            ['clio', 'Clio', 'yes'],
            ['coupe', 'Coupe', 'no'],
            ['espace', 'Espace', 'yes'],
            ['express', 'Express', 'no'],
            ['fluence', 'Fluence', 'yes'],
            ['fuego', 'Fuego', 'yes'],
            ['grand-espace', 'Grand Espace', 'yes'],
            ['grand-scenic', 'Grand Scenic', 'yes'],
            ['kadjar', 'Kadjar', 'yes'],
            ['kangoo', 'Kangoo', 'yes'],
            ['koleos', 'Koleos', 'yes'],
            ['laguna', 'Laguna', 'yes'],
            ['latitude', 'Latitude', 'yes'],
            ['master', 'Master', 'yes'],
            ['megane', 'Megane', 'yes'],
            ['modus', 'Modus', 'yes'],
            ['safrane', 'Safrane', 'yes'],
            ['scenic', 'Scenic', 'yes'],
            ['scenic-conquest', 'Scenic Conquest', 'no'],
            ['scenic-rx4', 'Scenic RX4', 'no'],
            ['symbol', 'Symbol', 'no'],
            ['talisman', 'Talisman', 'yes'],
            ['thalia', 'Thalia', 'no'],
            ['trafic', 'Trafic', 'yes'],
            ['twingo', 'Twingo', 'yes'],
            ['twizy', 'Twizy', 'yes'],
            ['vel-satis', 'Vel Satis', 'yes'],
            ['wind', 'Wind', 'yes'],
            ['zoe', 'Zoe', 'yes'],
        ],
    },
    {
        "olxBrand": "rolls-royce",
        "brand": "Rolls Royce",
        "models": [
            ['corniche', 'Corniche', 'no'],
            ['cullinan', 'Cullinan', 'yes'],
            ['dawn', 'Dawn', 'yes'],
            ['flying-spur-', 'Flying Spur', 'no'],
            ['ghost', 'Ghost', 'yes'],
            ['park-ward', 'Park Ward', 'no'],
            ['phantom', 'Phantom', 'yes'],
            ['silver-cloud', 'Silver Cloud', 'no'],
            ['silver-down', 'Silver Down', 'yes'],
            ['silver-seraph', 'Silver Seraph', 'yes'],
            ['silver-shadow', 'Silver Shadow', 'no'],
            ['silver-spirit', 'Silver Spirit', 'no'],
            ['silver-spur', 'Silver Spur', 'yes'],
            ['touring-limousine', 'Touring Limousine', 'no'],
            ['wraith', 'Wraith', 'yes'],
        ],
    },
    {
        "olxBrand": "rover",
        "brand": "Rover",
        "models": [
            ['100', '100', 'yes'],
            ['115', '115', 'no'],
            ['200', '200', 'yes'],
            ['213', '213', 'no'],
            ['214', '214', 'no'],
            ['216', '216', 'no'],
            ['218', '218', 'no'],
            ['220', '220', 'no'],
            ['25', '25', 'yes'],
            ['400', '400', 'yes'],
            ['414', '414', 'no'],
            ['416', '416', 'no'],
            ['418', '418', 'no'],
            ['420', '420', 'no'],
            ['45', '45', 'yes'],
            ['600', '600', 'yes'],
            ['618', '618', 'no'],
            ['620', '620', 'no'],
            ['623', '623', 'no'],
            ['75', '75', 'yes'],
            ['800', '800', 'yes'],
            ['820', '820', 'no'],
            ['825', '825', 'no'],
            ['827', '827', 'no'],
            ['city-rover', 'CityRover', 'yes'],
            ['mg', 'MG', 'no'],
            ['metro', 'Metro', 'no'],
            ['mini', 'Mini', 'no'],
            ['montego', 'Montego', 'no'],
            ['sd', 'SD', 'no'],
            ['streetwise', 'Streetwise', 'yes'],
        ],
    },
    {
        "olxBrand": "saab",
        "brand": "Saab",
        "models": [
            ["40789", "40789", "no"],
            ["900", "900", "yes"],
            ["96", "96", "no"],
            ["99", "99", "no"],
            ["9000", "9000", "yes"],
            ["40791", "40791", "no"],
            ["9-2x", "9-2X", "no"],
            ["9-3", "9-3X", "yes"],
            ["9-3x-sportkombi", "9-3X-Sportkombi", "no"],
            ["9-4x", "9-4X", "yes"],
            ["9-5", "9-5", "no"],
            ["9-7x", "9-7X", "no"],
            ["90", "90", "yes"],
        ],
    },
    {
        "olxBrand": "seat",
        "brand": "Seat",
        "models": [
            ['alhambra', 'Alhambra', 'yes'],
            ['altea', 'Altea XL', 'yes'],
            ['arona', 'Arona', 'yes'],
            ['arosa', 'Arosa', 'yes'],
            ['ateca', 'Ateca', 'yes'],
            ['cordoba', 'Cordoba', 'yes'],
            ['exeo', 'Exeo', 'yes'],
            ['ibiza', 'Ibiza', 'yes'],
            ['inca', 'Inca', 'yes'],
            ['leon', 'Leon', 'yes'],
            ['malaga', 'Malaga', 'yes'],
            ['marbella', 'Marbella', 'yes'],
            ['mii', 'Mii', 'yes'],
            ['ronda', 'Ronda', 'yes'],
            ['tarraco', 'Tarraco', 'yes'],
            ['terra', 'Terra', 'no'],
            ['toledo', 'Toledo', 'yes'],
        ],
    },
    {
        "olxBrand": "skoda",
        "brand": "Skoda",
        "models": [
            ['100', '100', 'yes'],
            ['105', '105', 'yes'],
            ['120', '120', 'yes'],
            ['130', '130', 'yes'],
            ['135', '135', 'yes'],
            ['Enyaq', 'Enyaq', 'no'],
            ['citigo', 'Citigo', 'yes'],
            ['fabia', 'Fabia', 'yes'],
            ['favorit', 'Favorit', 'yes'],
            ['felicia', 'Felicia', 'yes'],
            ['forman', 'Forman', 'yes'],
            ['kamiq', 'Kamiq', 'no'],
            ['karoq', 'Karoq', 'yes'],
            ['kodiaq', 'Kodiaq', 'yes'],
            ['octavia', 'Octavia', 'yes'],
            ['praktik', 'Praktik', 'no'],
            ['rapid', 'Rapid', 'yes'],
            ['roomster', 'Roomster', 'yes'],
            ['scala', 'Scala', 'yes'],
            ['superb', 'Superb', 'yes'],
            ['yeti', 'Yeti', 'yes'],
        ],
    },
    {
        "olxBrand": "smart",
        "brand": "Smart",
        "models": [
            ["crossblade", "Crossblade", "yes"],
            ["forfour", "Forfour", "yes"],
            ["fortwo", "Fortwo", "yes"], # OLX
            ["roadster", "Roadster", "yes"],
            ["roomster", "Roomster", "yes"],
        ],
    },
    {
        "olxBrand": "volvo",
        "brand": "Volvo",
        "models": [
            ['240', '240', 'yes'],
            ['244', '244', 'yes'],
            ['245', '245', 'yes'],
            ['262', '262', 'yes'],
            ['264', '264', 'yes'],
            ['340', '340', 'yes'],
            ['360', '360', 'yes'],
            ['440', '440', 'yes'],
            ['460', '460', 'yes'],
            ['480', '480', 'yes'],
            ['740', '740', 'yes'],
            ['744', '744', 'no'],
            ['745', '745', 'no'],
            ['760', '760', 'yes'],
            ['780', '780', 'no'],
            ['850', '850', 'yes'],
            ['855', '855', 'no'],
            ['940', '940', 'yes'],
            ['944', '944', 'no'],
            ['945', '945', 'no'],
            ['960', '960', 'yes'],
            ['965', '965', 'no'],
            ['amazon', 'Amazon', 'no'],
            ['c30', 'C30', 'yes'],
            ['c70', 'C70', 'yes'],
            ['polar', 'Polar', 'no'],
            ['s40', 'S40', 'yes'],
            ['s60', 'S60', 'yes'],
            ['s70', 'S70', 'yes'],
            ['s80', 'S80', 'yes'],
            ['s90', 'S90', 'yes'],
            ['v40', 'V40', 'yes'],
            ['v50', 'V50', 'yes'],
            ['v60', 'V60', 'yes'],
            ['v70', 'V70', 'yes'],
            ['v90', 'V90', 'yes'],
            ['xc-40', 'XC40', 'yes'],
            ['xc-60', 'XC60', 'yes'],
            ['xc-70', 'XC70', 'yes'],
            ['xc-90', 'XC90', 'yes'],
        ],
    },
    {
        "olxBrand": "subaru",
        "brand": "Subaru",
        "models": [
            ['1800-coupe', '1800 Coupe', 'no'],
            ['ascent', 'Ascent', 'no'],
            ['b9-tribeca', 'B9 Tribeca', 'yes'],
            ['baja', 'Baja', 'no'],
            ['brz', 'BRZ', 'yes'],
            ['forester', 'Forester', 'yes'],
            ['g3x-justy', 'G3X Justy', 'yes'],
            ['impreza', 'Impreza', 'yes'],
            ['justy', 'Justy', 'yes'],
            ['leone', 'Leone', 'no'],
            ['legacy', 'Legacy', 'yes'],
            ['levorg', 'Levorg', 'yes'],
            ['libero-', 'Libero', 'yes'],
            ['outback', 'Outback', 'yes'],
            ['svx', 'SVX', 'yes'],
            ['trezia', 'Trezia', 'yes'],
            ['tribeca', 'Tribeca', 'yes'],
            ['vivio', 'Vivio', 'no'],
            ['wrx-sti', 'WRX STI', 'no'],
            ['xt', 'XT', 'yes'],
            ['xv', 'XV', 'yes'],
        ],
    },
    {
        "olxBrand": "suzuki",
        "brand": "Suzuki",
        "models": [
            ['across', 'Across', 'no'],
            ['alto', 'Alto', 'yes'],
            ['baleno', 'Baleno', 'yes'],
            ['carry', 'Carry', 'yes'],
            ['celerio', 'Celerio', 'yes'],
            ['cappucino', 'Cappucino', 'yes'],
            ['grand-vitara', 'Grand Vitara', 'yes'],
            ['ignis', 'Ignis', 'yes'],
            ['jimny', 'Jimny', 'yes'],
            ['kizashi', 'Kizashi', 'yes'],
            ['liana', 'Liana', 'yes'],
            ['lj', 'LJ', 'yes'],
            ['reno', 'Reno', 'no'],
            ['samurai', 'Samurai', 'no'],
            ['sj', 'SJ', 'yes'],
            ['splash', 'Splash', 'yes'],
            ['super-carry', 'Super Carry', 'no'],
            ['swace', 'Swace', 'no'],
            ['swift', 'Swift', 'yes'],
            ['sx4', 'SX4', 'yes'],
            ['sx4-s-cross', 'SX4 S Cross', 'no'],
            ['vitara', 'Vitara', 'yes'],
            ['wagon-r-', 'Wagon R', 'yes'],
            ['x-90', 'X-90', 'no'],
            ['xl7', 'Xl7', 'no'],    
        ],
    },
    {
        "olxBrand": "tesla",
        "brand": "Tesla",
        "models": [
            ["tsla-model-s", "Model S", "yes"],
            ["model-3", "Model 3", "yes"],
            ["t-model-x", "Model X", "no"],
            ["t-model-y", "Model Y", "no"],
            ["roadster", "Roadster", "no"],
        ],
    },
    {
        "olxBrand": "toyota",
        "brand": "Toyota",
        "models": [
            ['4-runner', '4-Runner', 'yes'],
            ['alphard-', 'Alphard', 'no'],
            ['auris', 'Auris', 'yes'],
            ['avalon', 'Avalon', 'no'],
            ['avensis', 'Avensis', 'yes'],
            ['avensis-verso', 'Avensis Verso', 'no'],
            ['aygo', 'Aygo', 'yes'],
            ['camry', 'Camry', 'yes'],
            ['camry-solara', 'Camry Solara', 'no'],
            ['carina', 'Carina', 'yes'],
            ['celica', 'Celica', 'yes'],
            ['c-hr', 'C-HR', 'no'],
            ['corolla', 'Corolla', 'yes'],
            ['corolla-verso', 'Corolla Verso', 'no'],
            ['cressida', 'Cressida', 'yes'],
            ['crown', 'Crown', 'no'],
            ['dyna', 'Dyna', 'no'],
            ['fj', 'FJ', 'no'],
            ['gt86', 'GT86', 'yes'],
            ['harrier', 'Harrier', 'no'],
            ['hiace', 'Hiace', 'yes'],
            ['highlander', 'Highlander', 'no'],
            ['hilux', 'Hilux', 'yes'],
            ['iq', 'IQ', 'yes'],
            ['land-cruiser', 'Land Cruiser', 'yes'],
            ['lite-ace', 'Lite Ace', 'no'],
            ['matrix', 'Matrix', 'no'],
            ['mr2', 'MR2', 'yes'],
            ['paseo', 'Paseo', 'yes'],
            ['picnic', 'Picnic', 'yes'],
            ['previa', 'Previa', 'yes'],
            ['prius', 'Prius', 'yes'],
            ['prius-plus', 'Prius+', 'yes'],
            ['proace', 'Proace', 'yes'],
            ['rav-4', 'RAV4', 'yes'],
            ['sequoia', 'Sequoia', 'no'],
            ['sienna', 'Sienna', 'no'],
            ['starlet', 'Starlet', 'yes'],
            ['supra', 'Supra', 'yes'],
            ['tacoma', 'Tacoma', 'no'],
            ['tercel', 'Tercel', 'yes'],
            ['tundra', 'Tundra', 'no'],
            ['urban-cruiser', 'Urban Cruiser', 'yes'],
            ['venza', 'Venza', 'no'],
            ['verso', 'Verso', 'yes'],
            ['yaris', 'Yaris', 'yes'],
            ['yaris-verso', 'Yaris Verso', 'yes'],
        ],
    },
{
        "olxBrand": "ssangyong",
        "brand": "SsangYong",
        "models": [
            ["actyon", "Actyon", "yes"],
            ["family", "Family", "no"],
            ["korrando", "Korrando", "yes"],
            ["kyron", "Kyron", "yes"],
            ["musso", "Musso", "yes"],
            ["rexton", "Rexton", "yes"],
            ["rodius", "Rodius", "yes"],
            ["tivoli", "Tivoli", "yes"],
            ["tivoli-grand", "Tivoli Grand", "no"],
            ["xlv-", "XLV", "yes"],
        ],
    }   
]

SITE_SOURCES = [
    "RO-OLX",
    "RO-AUTOVIT",
    "DE-SCOUT24"
]